#=================================================
# https://github.com/danxiaonuo/anycastip
# Description: Automatic synchronization resources
# Lisence: MIT
# Author: danxiaonuo
# Blog: https://www.danxiaonuo.com
#=================================================

name: 自动同步anycastip

# 设置触发条件
on:
# 点击★开始触发更新
  watch:  
     types: [started]
  
# 每天的晚上3点钟自动更新
  schedule:
     - cron: '0 3 * * *'
     
# 环境变量
env:
   # 源码分支
   REPO_BRANCH: master
   # 时区设置
   TZ: Asia/Shanghai
   # 上传分支
   UPLOAD_BRANCH: true
   # Github 用户名
   GITHUB_USER_NAME: danxiaonuo
   # Github 邮箱
   GITHUB_USER_EMAIL: ${{ secrets.EMAIL }}
   # Github
   GITHUB_RROJECT: github.com/danxiaonuo/anycastip.git
   # 分支
   BRANCH: master
   # GITHUB项目路径
   GITHUB_PATH: /home/runner/work/AutoSync/AutoSync/anycastip
   
# 任务集
jobs:
  build:
    # 选择虚拟环境
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    
    # 运行步骤
    steps:
    
    # 检出master分支
    - name: 检出master分支
      uses: actions/checkout@master
      
    # 下载anycastip
    - name: 下载anycastip
      run: |
        curl -fsSL https://anycast.freecdn.workers.dev > anycastip.txt
        
    # 上传到分支
    - name: 上传到分支
      env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      run: |
          git init
          git config user.name $GITHUB_USER_NAME
          git config user.email $GITHUB_USER_EMAIL
          git add .
          git commit -a -m "Update resources"
          git push --force --quiet https://${{ secrets.RELEASE_TOKEN }}@$GITHUB_RROJECT HEAD:$BRANCH
