#=================================================
# https://github.com/danxiaonuo/packages
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: danxiaonuo
# Blog: https://www.danxiaonuo.com
#=================================================

name: 自动同步packages源码包

# 设置触发条件
on:
# 点击★开始触发更新
  watch:  
     types: [started]
     
# 环境变量
env:
   # 源码仓库地址
   REPO_URL: https://github.com/project-openwrt/packages
   # 源码分支
   REPO_BRANCH: master
   # 时区设置
   TZ: Asia/Shanghai
   # 上传分支
   UPLOAD_BRANCH: true
   # Github 用户名
   GITHUB_USER_NAME: danxiaonuo
   # Github 邮箱
   GITHUB_USER_EMAIL: ${{ secrets.EMAIL }}
   # Github
   GITHUB_RROJECT: github.com/danxiaonuo/packages.git
   # 分支
   BRANCH: master
   
   # 任务集
jobs:
  build:
    # 选择虚拟环境
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    
    # 运行步骤
    steps:
    
    # 检出master分支
    - name: 检出master分支
      uses: actions/checkout@master
      
    # 初始化系统环境
    - name: 初始化系统环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        docker rmi $(docker images -q)
        sudo -E swapoff /swapfile
        sudo -E rm -rf /swapfile /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get remove -y --purge azure-cli ghc zulu* hhvm llvm* firefox google* dotnet* powershell mysql* php* mssql-tools msodbcsql17
        sudo -E apt-get update -y
        sudo -E apt-get full-upgrade -y
        sudo -E apt-get install -y git git-core subversion curl wget
        sudo -E apt-get autoremove -y --purge
        sudo -E apt-get clean -y
        sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php
        
    # 克隆源码
    - name: 克隆源码
      run: |
        git clone $REPO_URL -b $REPO_BRANCH packages
        cd packages
        rm -rf *.md && rm -rf LICENSE
      
    # 上传到分支
    - name: 上传到分支
      env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      run: |
          cd packages/
          git init
          git config user.name $GITHUB_USER_NAME
          git config user.email $GITHUB_USER_EMAIL
          git add .
          git commit -a -m "Update packages"
          git push --force --quiet https://${{ secrets.RELEASE_TOKEN }}@$GITHUB_RROJECT HEAD:$BRANCH
